# Generated by Django 3.2.4 on 2021-06-13 16:45

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210613_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='manufacturer_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='number_id',
        ),
        migrations.AddField(
            model_name='item',
            name='uid',
            field=models.CharField(blank=True, editable=False, max_length=13),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to=app.models.upload_file_path),
            preserve_default=False,
        ),
    ]
