# Generated by Django 3.2.4 on 2021-06-13 16:50

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_item_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.ImageField(blank=True, upload_to=app.models.barcode_upload_file_path),
        ),
    ]
