# Generated by Django 3.2.4 on 2021-06-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_item_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_weight',
            field=models.IntegerField(default=1, help_text='Enter Unit Weight in KG'),
            preserve_default=False,
        ),
    ]
