# Generated by Django 3.2.4 on 2021-06-13 19:40

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_item_unit_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcoded_manual',
            field=models.ImageField(blank=True, upload_to=app.models.barcode_upload_file_path),
        ),
    ]
