# Generated by Django 3.2.4 on 2021-06-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_unit_weight_item_unit_weight_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uid',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
    ]
