# Generated by Django 3.2.4 on 2021-06-18 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_item_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='uid',
            field=models.CharField(blank=True, help_text='ID must be unique', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='buying_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
