# Generated by Django 3.2.4 on 2021-06-18 17:15

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.barcode_upload_file_path),
        ),
    ]
