# Generated by Django 3.2.4 on 2021-07-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_item_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit_weight_kg',
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Grams'), (2, 'Kilograms'), (3, 'Units')], default=1, null=True),
        ),
    ]
