# Generated by Django 3.2.4 on 2021-07-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210721_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='capacity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Grams'), (2, 'Kilograms'), (3, 'Units'), (4, 'Liter')], default=1, null=True),
        ),
    ]
