# Generated by Django 3.2.5 on 2021-09-08 18:19

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0021_auto_20210815_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_temprory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Grams'), (2, 'Kilograms'), (3, 'Units'), (4, 'Liter'), (5, 'MiliLeter')], default=1, null=True),
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app.models.upload_file_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
