# Generated by Django 3.2.5 on 2021-09-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210908_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uid',
            field=models.CharField(help_text='ID must be unique', max_length=20, unique=True),
        ),
    ]
