# Generated by Django 3.2.5 on 2021-09-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_item_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
