# Generated by Django 3.2.8 on 2021-10-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default='00.00', max_digits=20),
        ),
    ]
