# Generated by Django 3.2.8 on 2021-11-05 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0027_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uid',
            field=models.CharField(help_text='ID must be unique', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('user', 'uid')},
        ),
    ]
